name: vision_base_gpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip=21.2.4
  - pytorch==1.11.0
  - torchvision==0.12.0
  - cudatoolkit=11.3
  - pip:
    - mlflow==1.24.0
    - azureml-mlflow==1.39.0
    - matplotlib==3.5.1
    - tqdm==4.63.0
